name: Deploy to Azure Container Apps

on:
  # push:
  #   branches:
  #     - main
  #     - develop
  #   paths:
  #     - 'src/**'
  workflow_dispatch:

permissions:
    id-token: write
    contents: read

env:
  IMAGE_NAME: webapp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Sign in via Azure CLI
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Signin to Azure Container Registry
        run: |
          az acr login --name ${{ secrets.ACR_SERVER }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/src
          acrName: ${{ secrets.ACR_NAME}}
          containerAppName: ${{ secrets.ACA_NAME }}
          resourceGroup: ${{ secrets.RG_NAME }}
