name: Deploy to Azure

on:
  # push:
  #   branches:
  #     - main
  #     - develop
  #   paths:
  #     - 'src/**'
  #     - '.github/workflows/**'
  workflow_dispatch:

permissions:
    id-token: write
    contents: read

env:
  IMAGE_NAME: webapp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Sign in via Azure CLI
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Signin to Azure Container Registry
        run: |
          az acr login --name ${{ secrets.ACR_SERVER }}

      - name: Build and push container image to Azure Container Registry
        run: |
          az acr build \
            --registry ${{ secrets.ACR_SERVER }} \
            --image ${{ secrets.ACR_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            . 

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Sign in via Azure CLI
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.WEBAPP_NAME }}
          images: ${{ secrets.ACR_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
