name: Trigger auto deployment for x-zerotrust-paas-ca-0205

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/x-zerotrust-paas-ca-0205-AutoDeployTrigger-2e2bca25-221f-4b67-b344-891ba6b1aab2.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.XZEROTRUSTPAASCA0205_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.XZEROTRUSTPAASCA0205_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.XZEROTRUSTPAASCA0205_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: xzerotrustpaasacr.azurecr.io
          registryUsername: ${{ secrets.XZEROTRUSTPAASCA0205_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.XZEROTRUSTPAASCA0205_REGISTRY_PASSWORD }}
          containerAppName: x-zerotrust-paas-ca-0205
          resourceGroup: x-zerotrust-paas-rg
          imageToBuild: xzerotrustpaasacr.azurecr.io/x-zerotrust-paas-ca-0205:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


